NavBar implementation
4GeeksAcademy/exercise-collaborative-html-website-marcos-joel-joe-joan pull request #1
Opened 2024-10-28 19:56 UTC by Joangb85

NavBar implementation

2024-10-28 19:58 UTC, ScarzoJ requested changes

2024-10-28 19:58 UTC, ScarzoJ commented on website/assets/css/style.css
> +.container-fluid {
Separate styles

2024-10-28 20:26 UTC, ScarzoJ submitted a review, later dismissed
Ahora si

2024-10-28 20:27 UTC, JoeDE88 submitted a review, later dismissed
OK!

2024-10-28 20:35 UTC, Joangb85 commented on website/assets/css/style.css
> +.container-fluid {
Resolved

2024-10-29 11:38 UTC, ScarzoJ approved these changes, later dismissed

2024-10-30 18:04 UTC, ScarzoJ approved these changes, later dismissed

2024-10-30 18:05 UTC, JoeDE88 approved these changes, later dismissed
ok

2024-10-30 18:25 UTC, ScarzoJ approved these changes

2024-10-30 18:39 UTC, JoeDE88 approved these changes
muy bien!

2024-10-30 18:45 UTC, merged